name: plotbot_anaconda
channels:
  - conda-forge
dependencies:
  - python=3.12.4
  - numpy=1.26.4
  - numba>=0.59.0
  - pandas=2.2.2
  - zarr
  - xarray
  # - dask  # Temporarily removed to reduce environment size
  - matplotlib=3.9.2
  - cdflib>=1.3.1
  - beautifulsoup4=4.12.3
  - requests=2.32.2
  - python-dateutil=2.9.0.post0
  - scipy=1.15.2
  - pytest=7.4.4
  - termcolor=2.4.0
  - ipympl
  - pip
  - pip:
    - ipykernel
    - ipywidgets
    - pyspedas
    - dash
    - plotly
    - jupyter-dash
